import {Encode_Sans_Expanded } from "next/font/google";
import '../node_modules/@fortawesome/fontawesome-free/css/all.min.css'
import "./globals.css";
import Navbar from "./_components/Navbar";
import Footer from "./_components/Footer";

const Encode = Encode_Sans_Expanded({
subsets: ["latin"],
weight:['300', '400']
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${Encode.className} antialiased`}
      >
        <div className="flex flex-col justify-between min-h-screen">
          <Navbar/>
        <div className="container">
        {children}
        </div>
        <Footer/>
      </div>
      </body>
    </html>
  );
}
